### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlopen'

### ISSUE THREAD

**Issue by srikat** [earthpyy/alfred-pastebin#2]
Hi,

The workflow doesn't seem to be working. When I try it shows an error.

Log from the debugger:

```
[17:34:41.757] Pastebin[Universal Action] Processing complete
[17:34:41.763] Pastebin[Universal Action] Passing output '<?php

print( '<pre>' . print_r( tribe_get_custom_fields(), true ) . '</pre>' );

?>' to Run Script
[17:34:41.873] ERROR: Pastebin[Run Script] Traceback (most recent call last):
  File "/Users/sridharkatakam/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2A74E130-3478-489E-81CA-433F05ADDF24/script.py", line 13, in <module>
    get_paste_result()
  File "/Users/sridharkatakam/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2A74E130-3478-489E-81CA-433F05ADDF24/alfred_pastebin/functions.py", line 165, in get_paste_result
    response = create_paste(
  File "/Users/sridharkatakam/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2A74E130-3478-489E-81CA-433F05ADDF24/alfred_pastebin/functions.py", line 80, in create_paste
    api_user_key = get_api_user_key()
  File "/Users/sridharkatakam/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2A74E130-3478-489E-81CA-433F05ADDF24/alfred_pastebin/functions.py", line 52, in get_api_user_key
    response = urllib.urlopen(API_ENDPOINT + 'api_login.php', data=urllib.urlencode(payload))
AttributeError: module 'urllib' has no attribute 'urlopen'
[17:34:41.885] Pastebin[Run Script] Processing complete
[17:34:41.887] Pastebin[Run Script] Passing output '' to Conditional
[17:34:41.889] Pastebin[Conditional] Processing complete
[17:34:41.891] Pastebin[Conditional] Passing output '' to Post Notification
```

I've put my details in the Environment Variables tab.

Any idea?

**Comment by earthpyy** [comment]
Hi, thanks for reporting this. I'll push a fix very soon.

**Comment by earthpyy** [comment]
Hello, I've published a new version. Please try again :)

https://github.com/earthpyy/alfred-pastebin/releases/tag/v2.1.0

**Comment by srikat** [comment]
Thank you, works great!
